[package]
name = "demos-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
pin-project-lite = "0.2.16"
tokio = { version = "1.48.0", features = ["fs", "io-util", "macros", "rt-multi-thread", "time"] }
